;-----冒泡逆序排序-----
PUBLIC SORT
INCLUDE PACK.mac

DATAS SEGMENT COMMON 'DATA'

   P EQU 5    ;学生数
   NL EQU 15  ;NAME 完整长度
   SL EQU 4   ;SCORE 完整长度
   NL1 EQU 13 ;NAME 实际长度
   TEMP1 DB 0 ;存放实时学号
   TEMP2 DB 1

   NAMEA DB P DUP(NL1,?,NL1 DUP('$'))  ;存入5个名字且名字长度小于11
   SCOREASC DB P DUP(SL DUP('$'))   ;存入5个成绩，每个成绩（3字节）以$结尾
   RANK DW 0,1,2,3,4    ;相当于NAMEA和SCOREASC数组下标
   SCOREN DW 5 DUP(0)   ;存放数值以及排序完成的成绩
    
   X DB 3 DUP(?)   ; 存放0-255的数据
DATAS ENDS

ASSUME CS:CODES,DS:DATAS

CODES SEGMENT PUBLIC 'CODE'
	SORT PROC
	 PUSH AX
	 PUSH BX
	 PUSH CX
	 PUSH DX
	
	 MOV CX,P
	 DEC CX
	 LOOPS1:
	 PUSH CX
	 MOV BX,0
	 LOOPS2:
	 MOV AX,SCOREN[BX]
	 MOV DX,RANK[BX]
	 CMP AX,SCOREN[BX+2]
	 JGE NEXTS
	 ;通过比较SCORE来改变RANK的次序进行排序
	 XCHG AX,SCOREN[BX+2]
	 MOV SCOREN[BX],AX
	 XCHG DX,RANK[BX+2]
	 MOV RANK[BX],DX
	 NEXTS:
	 ADD BX,2
	 LOOP LOOPS2
	 POP CX
	 LOOP LOOPS1
	 POP DX
	 POP CX
	 POP BX
	 POP AX
	 RET
	SORT ENDP
CODES ENDS
END








