DATAS SEGMENT
    LIST DW 12,2545,22334,3211,4432,546
    MAX DW 0
DATAS ENDS

CODES SEGMENT
    ASSUME CS:CODES,DS:DATAS
START:
    MOV AX,DATAS
    MOV DS,AX
    MOV AX,MAX-LIST
    MOV BL,2
    IDIV BL
    MOV AH,0
    MOV CX,AX
    MOV SI,0
    GETMAX:
    CALL COMPARE
    LOOP GETMAX
   
    MOV AH,4CH
    INT 21H
    
    COMPARE PROC
      MOV AX,LIST[SI]
      CMP AX,MAX
      JLE LET0
      MOV MAX,AX
      LET0:
       ADD SI,2
       RET
    COMPARE ENDP
CODES ENDS
    END START
